#!/bin/bash
### py-convert-batch
###
### Copyright 2016 Mac Radigan
### All Rights Reserved

  d=${0%/*}; f=${0##*/}; n=${f%.*}; e=${f##*.}
  r=`readlink -f $d`

  srcdir=$1; shift

  for src in `find $srcdir -type f -name "*.py" | sort`; do
    dx=${src%/*}; fx=${src##*/}; nx=${fx%.*}; ex=${f##*.}
    dst=$dx/$nx.ipynb
    echo "converting $src $dst ..."
    $r/py-convert $src $dst
    echo "done."
  done

### *EOF*
